RM=rm -f
CC=gcc -g

build: libvy.so

clean:
	$(RM) *.o *.so

head:
	$(MAKE) build 2>&1 | head -n 20

pong:
	$(MAKE) -C ../pong clean build run

libvy.so: vy.o
	$(CC) -shared -o $@ $^

%.o: %.c
	$(CC) -fPIC -c -o $@ $<

vy.o: vy.c vy.h
